package com.willclay.forgeide.ui.icons;

import javax.imageio.ImageIO;
import java.awt.Image;
import java.awt.Taskbar;
import java.awt.Window;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;

/// The ForgeIDE application icon (the anvil), for window title bars and the
/// taskbar.
///
/// The icon ships as several pre-drawn PNG sizes rather than one large image.
/// [Window#setIconImages(List)] lets the platform pick the closest size for each
/// place it shows the icon — 16px in a title bar, 32px or more on a taskbar —
/// which looks much sharper than scaling a 256px image down on the fly.
///
/// The PNGs are generated by `packaging/icon/ForgeIconGenerator.java`, which
/// also writes the `.ico` embedded in the Windows launcher. Edit the generator,
/// not the PNGs.
public final class AppIcons
{
    private static final int[] SIZES = {16, 20, 24, 32, 40, 48, 64, 128, 256};
    private static final String RESOURCE = "/com/willclay/forgeide/icons/app/forge-%d.png";

    private static List<Image> images;

    private AppIcons() {}

    /// Every bundled size, smallest first. Missing sizes are skipped, so the
    /// list may be empty but is never null.
    public static synchronized List<Image> images()
    {
        if (images == null) images = List.copyOf(load());
        return images;
    }

    /// Gives the window the Forge icon. On platforms with an app-wide dock icon
    /// (macOS), sets that too.
    public static void install(Window window)
    {
        List<Image> icons = images();
        if (icons.isEmpty()) return;

        window.setIconImages(icons);

        if (Taskbar.isTaskbarSupported() && Taskbar.getTaskbar().isSupported(Taskbar.Feature.ICON_IMAGE))
        {
            Taskbar.getTaskbar().setIconImage(icons.getLast());
        }
    }

    private static List<Image> load()
    {
        List<Image> loaded = new ArrayList<>();
        for (int size : SIZES)
        {
            String path = RESOURCE.formatted(size);
            try (InputStream input = AppIcons.class.getResourceAsStream(path))
            {
                if (input == null) continue;
                Image image = ImageIO.read(input);
                if (image != null) loaded.add(image);
            }
            catch (IOException e)
            {
                System.err.println("Could not load app icon " + path + " (" + e.getMessage() + ")");
            }
        }
        return loaded;
    }
}
